# Generated by Django 4.1 on 2024-02-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todomodel_duedata_todomodel_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='duedata',
            new_name='duedate',
        ),
    ]
